### ISSUE TITLE
Scoped api token not working. Error 10000

### ISSUE THREAD

**Issue by maxfield-allison** [tiredofit/docker-traefik-cloudflare-companion#5]
As the title says, workaround by using Global API Key.

**Comment by Xpl0yt91** [comment]
Neither worked for me.

**Comment by maxfield-allison** [comment]
@Xpl0yt91 Try deleting the existing image and doing a fresh docker pull

**Comment by Xpl0yt91** [comment]
@maxfield-allison got it working man, cheers.

**Comment by maxfield-allison** [comment]
@Xpl0yt91 Good to hear! If you add the tag `:latest` to the compose or command, you should be able to just run a down/up to get it to pull the newest.

**Comment by tiredofit** [comment]
Thanks for sorting this out @maxfield-allison - I had a bit of an issue in the past 3 weeks with the Docker Images building on a fritz. It's been resolved now.

**Comment by maxfield-allison** [comment]
Good to hear! Thanks again for this excellent utility.

**Comment by htpcBeginner** [comment]
This PR would address the token support: 

https://github.com/tiredofit/docker-traefik-cloudflare-companion/pull/10

**Comment by tiredofit** [comment]
Now rewritten as `tiredofit/traefik-cloudflare-companion:6.0.0` in Python3

Ignore what I wrote above, that was using an older method.
Simply use your Scoped token in `CF_TOKEN` and set `CF_EMAIL=None`.

**Comment by MaartenKleijwegt** [comment]
Can this be reopened? I'm still experiencing this. When setting _CONTAINER_LOG_LEVEL=DEBUG_

The logs show:
```
 curl -X GET "https://api.cloudflare.com/client/v4/zones/REDACTED/dns_records?name=REDACTED" \
            -H "User-Agent: python-cloudflare/2.8.13/python-requests/2.24.0/python/3.8.5" \
            -H "Content-Type: application/json" \
            -H "X-Auth-Email: None" \
            -H "X-Auth-Key: REDACTED"
```

Suggesting the python library is now trying to authenticate using email "None" and still using an X-AUTH-KEY. when using an API token it should be 

```
~$ curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
>      -H "Authorization: Bearer vh9awGupxxxxxxxxxxxxxxxxxxx" \
>      -H "Content-Type:application/json" | jq
```

I'm reusing my API token from cloudflare-ddns so the keys must be right

**Comment by tiredofit** [comment]
I've screwed this up. I'm going to get some time to look into this in a couple days.

**Comment by tiredofit** [comment]
`6.0.2` will fix this. I have just tested a few scenarios.

**Comment by nearcatch** [comment]
I used a scoped API token with `CF_EMAIL` unset and it worked perfectly.

**Comment by MaartenKleijwegt** [comment]
Absolutely correct. As mentioned by @tiredofit he fixed it (for me) with 6.0.2. Working as intended now. I guess this can be closed

**Comment by maxfield-allison** [comment]
Fixed by #10
